name: Aliyun
on:
  workflow_dispatch:
    inputs:
      BT:
        description: '磁力链接'
        required: false
      HTTP:
        description: '种子下载链接'
        required: false
      choice:
        description: 'BT文件选择 例: --select-file=2,4,5,10,12'
        required: false
      Token-Aliyun:
        description: 'Aaliyuntoken'
        required: false
      Token-Onedrive:
        description: 'Onedrive-token [Login-Token](https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=78d4dc35-7e46-42c6-9023-2d39314433a5&response_type=code&redirect_uri=http://localhost/onedrive-login&response_mode=query&scope=offline_access%20User.Read%20Files.ReadWrite.All)'
        required: false

jobs:
  OfflineDownload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt install -y aria2
      - name: Run Download
        run: |
          mkdir Server_Upload
          cd Server_Upload
          if [ -n "${{ github.event.inputs.BT }}" ]; then
            aria2c '${{ github.event.inputs.BT }}' --seed-time=0
          else
            wget "${{ github.event.inputs.HTTP }}" -O 1.torrent
            aria2c 1.torrent --seed-time=0${{ github.event.inputs.choice }}
          fi
          rm -rf 1.torrent
      - name: Run Upload
        run: |
          ls
          if [ -n "${{ github.event.inputs.Token-Onedrive }}" ]; then
            cd Onedrive
            mv /home/runner/work/Offline_Downloads/Offline_Downloads/Server_Upload /home/runner/work/Offline_Downloads/Offline_Downloads/Onedrive
            chmod +x OneDriveUploader
            ./OneDriveUploader -a ${{ github.event.inputs.Token-Onedrive }}
            ./OneDriveUploader -s "Server_Upload"
          else
            cd /home/runner/work/Offline_Downloads/Offline_Downloads/aliyunpan-v0.2.7-linux-amd64
            ./aliyunpan login -RefreshToken=${{ github.event.inputs.Token-Aliyun }}
            ./aliyunpan upload /home/runner/work/Offline_Downloads/Offline_Downloads/Server_Upload /影视
            ./aliyunpan logout -y
          fi

