name: BiliBili Download
on:
  workflow_dispatch:
    inputs:
      BiliBili:
        description: 'BiliBili链接'
        required: true
      Choice:
        description: '分P选择(3、1,3,5、1-3、all)'
        required: true
      Token-Aliyun:
        description: 'Aaliyuntoken'
        required: false
      Token-Onedrive:
        description: 'Onedrive-token (参照README.md)'
        required: false
jobs:
  OfflineDownload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt install -y aria2
      - name: Run Download
        run: |
          cd BiliBili
          ./BBDown -c "SESSDATA=" -p ${{ github.event.inputs.Choice }} "${{ github.event.inputs.BiliBili }}"
      - name: Run Upload
        run: |
          if [ -n "${{ github.event.inputs.Token-Onedrive }}" ]; then
            cd OnedriveCli
            mv /home/runner/work/Offline_Downloads/Offline_Downloads/Server_Upload /home/runner/work/Offline_Downloads/Offline_Downloads/Onedrive
            chmod +x OneDriveUploader
            ./OneDriveUploader -a ${{ github.event.inputs.Token-Onedrive }}
            ./OneDriveUploader -t 20 -b 50 -s "Server_Upload"
          else
            cd /home/runner/work/Offline_Downloads/Offline_Downloads/aliyunpan-v0.2.7-linux-amd64
            ./aliyunpan login -RefreshToken=${{ github.event.inputs.Token-Aliyun }}
            ./aliyunpan upload /home/runner/work/Offline_Downloads/Offline_Downloads/Server_Upload /影视
            ./aliyunpan logout -y
          fi
