name: Film Download
on:
  workflow_dispatch:
    inputs:
      BT:
        description: 'BT链接'
        required: true
      Token:
        description: 'Aaliyuntoken'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Download
        run: |
          sudo apt-get update
          sudo apt install -y aria2
          mkdir Server_Upload
          cd Server_Upload
          aria2c '${{ github.event.inputs.BT }}' --seed-time=0
          cd /home/runner/work/Amine/Amine
          ls
          cd aliyunpan-v0.2.7-linux-amd64
          ./aliyunpan login -RefreshToken=${{ github.event.inputs.Token }}
          ./aliyunpan upload /home/runner/work/Amine/Amine/Server_Upload /影视
      - name: Cleanup Files
        run: |
          cd /home/runner/work/Amine/Amine/Server_Upload
          rm -rf *
          cd /home/runner/work/Amine/Amine
          rm -rf aliyunpan-v0.2.7-linux-amd64
