name: OfflineDownload
on:
  workflow_dispatch:
    inputs:
      BT:
        description: '磁力链接'
        required: false
      HTTP:
        description: '种子下载链接'
        required: false
      choice:
        description: 'BT文件选择 例: --select-file=2,4,5,10,12'
        required: false
      Token:
        description: 'Aaliyuntoken'
        required: true
jobs:
  OfflineDownload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Download
        run: |
          sudo apt-get update
          sudo apt install -y aria2
          mkdir Server_Upload
          cd Server_Upload

          if [ -n "${{ github.event.inputs.BT }}" ]; then
            aria2c '${{ github.event.inputs.BT }}' --seed-time=0
          else
            wget "${{ github.event.inputs.HTTP }}" -O 1.torrent
            aria2c 1.torrent --seed-time=0${{ github.event.inputs.choice }}
          fi
          rm -rf 1.torrent
      - name: Run Upload
        run: |
          ls
          cd /home/runner/work/Amine/Amine/aliyunpan-v0.2.7-linux-amd64
          ./aliyunpan login -RefreshToken=${{ github.event.inputs.Token }}
          ./aliyunpan upload /home/runner/work/Amine/Amine/Server_Upload /影视
      - name: Cleanup Files
        run: rm -rf /home/runner/work/Amine/Amine/Server_Upload
