name: Offline Download
on:
  workflow_dispatch:
    inputs:
      Tool:
        description: '下载器'
        required: true
        options: [aria, transmission]
        default: aria
      BT:
        description: '磁力链接或文件直链'
        required: false
      HTTP:
        description: '种子下载直链链接'
        required: false
      choice:
        description: 'BT文件选择 例: --select-file=2,4,5,10,12'
        required: false
      Token-Aliyun:
        description: 'Aaliyuntoken'
        required: false
      OnedriveDir:
        description: 'Onedrive上传路径'
        required: false

jobs:
  OfflineDownload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt install -y aria2
          sudo apt install -y transmission-cli
      - name: Run Download
        run: |
          mkdir Server_Upload
          cd Server_Upload
          if [ -n "${{ github.event.inputs.BT }}" ]; then
            if [[ "${{ inputs.Tool }}" == *aria* ]]; then
                aria2c '${{ github.event.inputs.BT }}' --seed-time=0
            else
                transmission-cli "${{ github.event.inputs.BT }}"
            fi
          else
            if [[ "${{ inputs.Tool }}" == *aria* ]]; then
                wget "${{ github.event.inputs.HTTP }}" -O 1.torrent
                aria2c 1.torrent --seed-time=0${{ github.event.inputs.choice }}
            else
                transmission-cli "${{ github.event.inputs.HTTP }}"
            fi
          fi
          rm -rf 1.torrent
      - name: Run Upload
        run: |
          ls
          if [ -n "${{ github.event.inputs.Token-Aliyun }}" ]; then
            cd /home/runner/work/Offline_Downloads/Offline_Downloads/aliyunpan-v0.2.7-linux-amd64
            ./aliyunpan login -RefreshToken=${{ github.event.inputs.Token-Aliyun }}
            ./aliyunpan upload /home/runner/work/Offline_Downloads/Offline_Downloads/Server_Upload /影视
            ./aliyunpan logout -y
          else
            cd OnedriveCli
            mv /home/runner/work/Offline_Downloads/Offline_Downloads/Server_Upload /home/runner/work/Offline_Downloads/Offline_Downloads/OnedriveCli
            chmod +x OneDriveUploader
            if [ -n "${{ github.event.inputs.OnedriveDir }}" ]; then
              ./OneDriveUploader -s "Server_Upload" -r "${{ github.event.inputs.OnedriveDir }}"
            else
              ./OneDriveUploader -s "Server_Upload"
            fi  
          fi
