name: Get OneDrive Token

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'http://loaclhost 开头的整个url内容'
        required: true
jobs:
  Get-Token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Get Token
        run: |
          cd OnedriveCli
          ./OneDriveUploader -a "${{ inputs.URL }}"
          sed -i 's/"ThreadNum": "2"/"ThreadNum": "20"/' auth.json
          sed -i 's/"BlockSize": "10"/"BlockSize": "50"/' auth.json
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update files from GitHub Action"
          git push -f origin main
