name: Resize and Merge Disk

on:
  workflow_dispatch:
jobs:
  resize-and-merge-disk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Resize Disk
      run: |
        sudo umount /dev/sdb1
        sudo resize2fs /dev/sdb1 5G
        sudo parted /dev/sdb resizepart 1 5GB
        sudo pvcreate /dev/sdb1
        sudo vgextend /dev/sdb1
        sudo lvextend -l +100%FREE /
        sudo resize2fs /
